language: node_js
node_js:
- 6.0.0
branches:
  only:
  - master
install:
- npm i ap-io
script: node_modules/ap-io/bin/ap-io -g --verbose --baseurl '/elements'
after_success:
- chmod +x ./deploy.sh
- ./deploy.sh
