language: node_js
node_js:
- 4.1
branches:
  only:
  - master
before_install:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
install:
- npm install
- bower install
before_script:
- chmod +x ./site_generator/generate.sh
script: "./site_generator/generate.sh --prod"
after_success:
- chmod +x ./site_generator/deploy.sh
- "./site_generator/deploy.sh"
