title: Jekyll is awesome for blogs
email: tejankarajinkya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Test repo for experimenting with jekyll
baseurl: "/elements" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
permalink: none
markdown: kramdown
include:
  - ".nojekyll"
exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "*.todo"
  - "*.sh"
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "elements"
      type: "pages"
    values:
      layout: "element"
