#!/bin/bash

((total = 0))

while read -r line; do
	cat_name="${line%\"*}"
	cat_name="${cat_name#*\"}"
	((count = 0))

	echo "    \"elements\": ["
	for file in */*.html; do
		if grep "component_category: $cat_name" "$file" &>/dev/null; then
			el_name=$(grep 'component_name:' "$file" | awk '{ print $2 }')
			echo "        \"https://github.com/atomelements/$el_name\","
			((count++))
		fi
	done
	echo "    ]"

	echo "   $cat_name elements = $((count))"
	((total += count))
done < <(grep 'name' ../_data/categories.json | awk '{ print $2 }')

echo ""
echo "All elements = $((total))"
